# ==========================================
# CẤU HÌNH SERVER & EUREKA
# ==========================================
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
server.port=8811
spring.application.name=user-service
# Cấu hình Eureka Server
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# ==========================================
# CẤU HÌNH DATABASE (MYSQL - XAMPP)
# ==========================================
# Tự động tạo database 'users' nếu chưa tồn tại
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME:ecommerce_db_2zgs_user}
spring.datasource.password=${DB_PASSWORD:h1eYen85LYwa9g6GJVE1oZr8FfwdIBGi}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
```

---

## Thêm env trên Render (user-service → Environment)
```
DATABASE_URL = postgresql://ecommerce_db_2zgs_user:h1eYen85LYwa9g6GJVE1oZr8FfwdIBGi@dpg-d76ckd8ule4c73erd3g0-a/ecommerce_db_2zgs

# ==========================================
# JPA / HIBERNATE (Chuẩn Spring Boot 3)
# ==========================================
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ==========================================
# CẤU HÌNH THÔNG BÁO LỖI TÙY CHỈNH
# ==========================================
error.404.schema.details=The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable
error.406.schema.details=This request is not acceptable. Supported MIME types are application/json
