# ==========================================
# CẤU HÌNH SERVER & EUREKA
# ==========================================
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
server.port=8812
spring.application.name=product-recommendation-service

# Đăng ký với Eureka Server

# ==========================================
# CẤU HÌNH DATABASE (MYSQL - XAMPP)
# ==========================================
# Tự động tạo database 'recommendation_db' nếu chưa có trong XAMPP
#//
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=false


# JPA / HIBERNATE

spring.jpa.show-sql=true
# Hibernate 6 tự động nhận diện Dialect cho MySQL 8+, không nhất thiết phải chỉ định
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# ==========================================
# CẤU HÌNH FEIGN CLIENT (Tùy chọn cho Spring Boot 3)
# ==========================================
# Giúp theo dõi quá trình gọi API giữa các service nếu cần debug
logging.level.com.rainbowforest.productrecommendationservice.feignclient=DEBUG
