# ==========================================
# CẤU HÌNH SERVER & EUREKA
# ==========================================
server.port=8810
spring.application.name=product-catalog-service
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

# Eureka Server registration


# ==========================================
# CẤU HÌNH DATABASE (MYSQL - XAMPP)
# ==========================================
# Tự động tạo database 'product_catalog' nếu chưa tồn tại
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=false

# ==========================================
# JPA / HIBERNATE (Spring Boot 3 / Hibernate 6)
# ==========================================
spring.jpa.show-sql=true
# Hibernate 6 tự nhận diện Dialect rất tốt, nhưng khai báo rõ cho MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Tắt tính năng query metadata của Hibernate để khởi động nhanh hơn (tùy chọn)
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
